language: minimal
addons:
  apt:
    packages:
      - docker-ce
    sources:
      - sourceline: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable test'
        key_url: 'https://download.docker.com/linux/ubuntu/gpg'
env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
  matrix:
    - SWARMPIT_VERSION=edge
script:
  - bash deploy-image.sh
